import React, { createContext, useContext, useEffect, useState } from 'react';

const LangContext = createContext();

export const useLang = () => {
  const context = useContext(LangContext);
  if (!context) throw new Error('useLang must be used within LangProvider');
  return context;
};

const dictionaries = {
  en: {
    language: 'Language',
    english: 'English',
    russian: 'Russian',
    kyrgyz: 'Kyrgyz',
    logo: 'CWD Rental',
    logoAlt: 'CWD Rental Kyrgyzstan fleet logo',
    tagline: 'Kyrgyzstan fleet',
    cars: 'Cars',
    offices: 'Offices',
    contact: 'Contact',
    faq: 'FAQ',
    admin: 'Admin',
    account: 'Account',
    addCar: 'Add car',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    heroTitle: 'Stay on the road with CWD for a privileged rental experience',
    heroImageAlt: 'Modern car on a scenic travel road',
    heroChips: ['Issyk-Kul beaches', 'Tian Shan gorges', 'Summer and ski roads'],
    heroLead: 'Premium cars for lake weekends, mountain routes, airport pickups, and confident travel across Kyrgyzstan.',
    cwdMeaning: 'CWD - Comfort Wheels Drive: comfortable cars, trusted wheels, and freedom to drive Kyrgyzstan.',
    profilePhoto: 'Profile photo',
    uploadProfilePhoto: 'Upload photo',
    changeProfilePhoto: 'Change photo',
    payment: 'Payment',
    securePayment: 'Secure payment',
    paymentTitle: 'Tokenized rental payment',
    paymentLead: 'Card details stay inside the payment provider layer. The backend receives only a token, rental ID, and amount.',
    paymentProvider: 'Payment provider',
    paymentMethod: 'Payment method',
    card: 'Card',
    digitalWallet: 'Digital wallet',
    tokenizedPaymentBox: 'Secure provider token',
    tokenizedPaymentText: 'Demo mode simulates Stripe or PayPal tokenization. No raw card number is stored or sent to the backend.',
    paymentStatus: 'Payment status',
    amountDue: 'Amount due',
    payNow: 'Pay now',
    continueToPayment: 'Continue to payment',
    paymentSuccess: 'Payment confirmed through the demo webhook. Your rental is now confirmed.',
    paymentAlreadyPaid: 'Already paid',
    paymentRentalNotFound: 'Rental was not found in your account.',
    refundReason: 'Refund reason',
    refundReasonPlaceholder: 'Tell us why this booking should be cancelled or refunded.',
    customerCancellationReason: 'Customer cancellation request',
    refundCreated: 'Refund created and rental cancelled.',
    pickup: 'Pick up office',
    dropoff: 'Drop off office',
    pickupDate: 'Pick up date',
    dropoffDate: 'Drop off date',
    pickupTime: 'Pick up time',
    dropoffTime: 'Drop off time',
    searchCars: 'Search cars',
    liveFleet: 'Live fleet',
    carsForRent: 'Cars for rent',
    approvedCarsAvailable: ({ count = 0 } = {}) => count === 1 ? '1 approved car is available' : `${count} approved cars are available`,
    noCarsFound: 'No cars found',
    noCarsText: 'Try adjusting your search or filters. There are plenty of cars available for rent.',
    clearFilters: 'Clear filters',
    clearAll: 'Clear all',
    filters: 'Filters',
    search: 'Search',
    pricePerDay: 'Price per day',
    transmission: 'Transmission',
    fuel: 'Fuel',
    sortBy: 'Sort by',
    lowToHigh: 'Price: Low to high',
    highToLow: 'Price: High to low',
    newestFirst: 'Newest first',
    carsFound: 'cars found',
    available: 'Available',
    seats: 'seats',
    viewDetails: 'View details',
    backToCars: 'Back to cars',
    verifiedFleet: 'Verified fleet',
    readyToBook: 'Ready to book?',
    bookNow: 'Book now',
    backendRentalHint: 'Pick your dates and the rental will be created through the backend.',
    book: 'Book',
    confirmBooking: 'Confirm booking',
    loginToBook: 'Login to book',
    rentalCreated: 'Rental created',
    rentalCreatedText: 'Your booking is now saved in the Spring Boot backend.',
    viewMyRentals: 'View my rentals',
    welcomeBack: 'Welcome back',
    signIn: 'Sign in',
    email: 'Email',
    password: 'Password',
    signingIn: 'Signing in...',
    noAccount: 'No account yet?',
    createPartnerAccount: 'Create a partner account',
    createAccount: 'Create account',
    creatingAccount: 'Creating account...',
    fullName: 'Full name',
    phone: 'Phone',
    confirmPassword: 'Confirm password',
    backToLogin: 'Back to login',
    partnerAccess: 'Partner access',
    officesNetwork: 'Kyrgyzstan network',
    officesLead: 'Choose a pickup point from airport counters and city offices across Bishkek, Osh, Issyk-Kul, Karakol, and Jalal-Abad.',
    airportOffice: 'Airport office',
    cityOffice: 'City office',
    city: 'City',
    code: 'Code',
    address: 'Address',
    workingHours: 'Working hours',
    availableServices: 'Available services',
    directions: 'Directions',
    officeServiceFallback: 'This service is available at this office. Contact the branch for exact timing and requirements.',
    manageCars: 'Manage cars',
    adminFleet: 'Admin fleet',
    partnerGarage: 'Partner garage',
    manageCarsAdminText: 'Approve, reject, edit, or create cars.',
    manageCarsPartnerText: 'Submit your cars for admin approval and manage your listings.',
    refresh: 'Refresh',
    closeForm: 'Close form',
    submitPartnerCar: 'Submit partner car',
    createApprovedCar: 'Create approved car',
    editCar: 'Edit car',
    brand: 'Brand',
    model: 'Model',
    year: 'Year',
    vin: 'VIN, 11-17 chars',
    description: 'Description',
    carImages: 'Car images, up to 3 from your device',
    image: 'Image',
    chooseFile: 'Choose file',
    noFileChosen: 'No file chosen',
    removeImage: 'Remove image',
    updateCar: 'Update car',
    createCar: 'Create car',
    sendForApproval: 'Send for approval',
    cancel: 'Cancel',
    delete: 'Delete',
    approve: 'Approve',
    reject: 'Reject',
    security: 'Security',
    backendUsers: 'Backend users',
    adminWorkspace: 'Admin workspace',
    controlCenter: 'Control center',
    adminControl: 'Admin control',
    rentalHistory: 'Rental history',
    rentals: 'Rentals',
    users: 'Users',
    user: 'User',
    car: 'Car',
    dates: 'Dates',
    total: 'Total',
    allRoles: 'All roles',
    allProviders: 'All providers',
    allStatuses: 'All statuses',
    active: 'Active',
    banned: 'Banned',
    ban: 'Ban',
    unban: 'Unban',
    reason: 'Reason',
    actions: 'Actions',
    banUser: 'Ban user',
    bannedReason: 'Banned reason',
    writeBanReason: 'Write why this user is banned...',
    profile: 'Profile',
    myRentals: 'My rentals',
    partnerDashboard: 'Partner dashboard',
    myAccount: 'My account',
    backendRentals: 'Backend rentals',
    noRentals: 'No rentals yet. Pick a car and create your first booking.',
    totalSpend: 'Total spend',
    provider: 'Provider',
    role: 'Role',
    status: 'Status',
    location: 'Location',
    auto: 'Auto',
    manual: 'Manual',
    gas: 'Gas',
    diesel: 'Diesel',
    hybrid: 'Hybrid',
    bookingSummary: 'Booking summary',
    bookingDetails: 'Booking details',
    availableCars: 'Available cars',
    days: 'Days',
    loginSideTitle: 'Rent, list, approve and manage cars from one elegant workspace.',
    loginSideText: 'Manage your rentals and approved fleet from a clean, secure workspace.',
    oauthLoginFailed: 'OAuth login failed',
    oauthNotConfigured: 'Google login is not configured yet. Check GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, and Google redirect URI.',
    connectingGoogle: 'Connecting to Google...',
    passwordPlaceholder: 'Your password',
    createYourAccount: 'Create your account',
    passwordsDoNotMatch: 'Passwords do not match',
    registrationFailed: 'Registration failed',
    loading: 'Loading...',
    loadingCars: 'Loading cars...',
    loadingRentals: 'Loading rentals...',
    loadingUsers: 'Loading users...',
    noCarsYet: 'No cars yet. Add your first car to start.',
    noBackendRentals: 'No backend rentals yet.',
    noUsersMatch: 'No users match the selected filters.',
    carUpdated: 'Car updated. Partner edits return to pending approval.',
    adminCarCreated: 'Admin car created and approved immediately.',
    carSubmitted: 'Car submitted to admin for approval.',
    carDeleted: 'Car deleted.',
    deleteCarConfirm: 'Remove this car from the backend?',
    deleteUserConfirm: ({ email }) => `Remove user ${email}? This is a soft delete in the database.`,
    banReasonRequired: 'Ban reason is required',
    banning: 'Banning...',
    brandModelVinRequired: 'Brand, model, and VIN are required',
    vinMinLength: 'VIN must be at least 11 characters',
    priceGreaterThanZero: 'Price must be greater than zero',
    edit: 'Edit',
    perDay: 'per day',
    backendRental: 'Rentals',
    rentalDays: ({ days }) => `${days} rental days`,
    creatingRental: 'Creating rental...',
    activeRentals: 'Active rentals',
    notSet: 'Not set',
    hi: 'Hi',
    id: 'ID',
    searchUsers: 'Search ID, name, or email',
    complete: 'Complete',
    findMyRental: 'Find my rental',
    cancelRental: 'Cancel rental',
    rentalSupport: 'Rental support',
    rentalId: 'Rental ID',
    enterRentalId: 'Enter rental ID',
    checking: 'Checking...',
    cancelRentalLead: 'Admins can cancel directly. Partners can verify the rental and contact support.',
    rentalCancelled: 'Rental cancelled in the backend.',
    rentalNotFound: 'Rental not found in your account.',
    rentalFoundContactSupport: 'Your rental was found. Backend cancellation is admin-only, so contact support or an admin to cancel it.',
    dashboardLead: 'Track rentals, manage your partner cars, and keep every trip organized from one polished workspace.',
    verifiedPartner: 'Verified partner workspace',
    profileDetails: 'Profile details',
    quickActions: 'Quick actions',
    accountSecurity: 'Account security',
    accountSecurityText: 'Your account uses backend authentication, provider tracking, and role-based access.',
    planTrip: 'Plan a trip',
    exploreOffices: 'Explore offices',
    requestSupport: 'Request support',
    cancelHelp: 'Cancel help',
    recentActivity: 'Recent activity',
    noActivity: 'No rental activity yet. Start with a car and your first route will appear here.',
    supportWorkflow: 'Support workflow',
    cancelStepOne: 'Enter rental ID',
    cancelStepTwo: 'We verify ownership and status',
    cancelStepThree: 'Admin or support completes the cancellation',
    saferCancelTitle: 'Safe cancellation, clear ownership',
    saferCancelText: 'Partners can verify their rental before support action. Admins can cancel directly through the backend status endpoint.',
    directSupport: 'Direct support',
    adminDashboardLead: 'Review fleet approvals, rental status, users, and platform safety from one command center.',
    verifiedAdmin: 'Verified admin workspace',
    adminOverview: 'Operations overview',
    fleetControl: 'Fleet control',
    fleetControlText: 'Approve partner cars, create official cars, and keep listings reliable.',
    rentalControlText: 'Complete or cancel backend rentals and monitor customer trip history.',
    userControlText: 'Filter users, ban risky accounts with reasons, and keep access clean.',
    commandShortcuts: 'Command shortcuts',
    reviewCars: 'Review cars',
    reviewRentals: 'Review rentals',
    reviewUsers: 'Review users',
    platformHealth: 'Platform health',
    platformHealthText: 'Backend data is connected through protected admin APIs with role-based access.',
    name: 'Name',
    message: 'Message',
    send: 'Send',
    messageSent: 'Message sent! (Demo)',
    contactSupportDetails: 'For more details, contact our support team.',
    pageNotFound: 'Page not found',
    pageNotFoundText: 'Sorry, the requested page does not exist.',
    home: 'Home',
    corporate: 'Corporate',
    modify: 'Modify booking',
    cancelBookingFooter: 'Cancel booking',
    help: 'Help',
    about: 'About',
    feedback: 'Feedback',
    other: 'Other',
    destinations: 'Destinations',
    fleet: 'Fleet',
    policies: 'Policies',
    privacy: 'Privacy',
    legal: 'Legal',
    terms: 'Terms',
    copyright: '© 2026 CWD Rental. All rights reserved.',
    faqItems: [
      { q: 'How do I book a car?', a: 'Choose pickup and return dates, open a car card, review the details, then confirm the booking. The request is saved through the Spring Boot backend.' },
      { q: 'Can partners add their own cars?', a: 'Yes. Partners can submit cars with fuel, transmission, price, VIN, description, and up to three local images. Admin approval is required before the car appears in the public fleet.' },
      { q: 'How does admin approval work?', a: 'Admins review submitted cars, approve reliable listings, reject incorrect data, manage bookings, and control user access from the admin workspace.' },
      { q: 'What payment methods are supported?', a: 'Payment and deposit details are confirmed at pickup with the office team. The current webapp focuses on booking, account, fleet, and admin workflows.' },
      { q: 'Can I change or cancel a booking?', a: 'Partners can check their rental in the account area. Admins can cancel or complete rentals in the backend dashboard, and support can help with date changes.' },
      { q: 'Which languages are supported?', a: 'The interface supports English, Russian, and Kyrgyz. Use the vertical language switcher in the header to change the whole UI.' },
      { q: 'Which offices are available?', a: 'The project includes airport and city offices for Manas, Osh, Bishkek, Issyk-Kul, Karakol, and Jalal-Abad with tourism-focused service details.' },
    ],
    aboutEyebrow: 'Built in 2026 by AIU students',
    aboutTitle: 'A tourism-first car rental platform for Kyrgyzstan',
    aboutLead: 'This webapp was created by Ala-Too International University students in 2026 to support tourism, make travel inside the country easier, and connect visitors with comfortable local mobility.',
    aboutStoryTitle: 'Student project with a real travel mission',
    aboutStoryText: 'CWD Rental combines a React frontend and Spring Boot backend to show how a modern university project can solve a practical tourism problem: booking trusted cars, discovering offices, and helping partners publish vehicles safely.',
    aboutTourismTitle: 'Designed for comfort inside the country',
    aboutTourismText: 'The experience is focused on Kyrgyzstan routes: airport pickups, city offices, mountain trips, lake travel, regional roads, and simple communication for guests who want confidence before the road begins.',
    aboutFleetTitle: 'Fleet, partners, and admin control in one ecosystem',
    aboutFleetText: 'Partners can add cars with images and details, while admins approve listings, manage rentals, ban unsafe users with reasons, and keep the marketplace clean.',
    aboutStats: [
      { value: '2026', label: 'project launch year' },
      { value: '3', label: 'interface languages' },
      { value: '7', label: 'tourism offices' },
      { value: '24/7', label: 'airport pickup support' },
    ],
    aboutHighlights: [
      'Created by Ala-Too International University students',
      'Supports domestic tourism and regional travel',
      'Built with React, Spring Boot, JWT, OAuth2, and PostgreSQL',
      'Partner and admin workflows are connected to the backend',
    ],
    contactEyebrow: 'Project contacts',
    contactTitle: 'Talk to the CWD Rental team',
    contactLead: 'Questions about cars, offices, partner listings, admin support, or the project idea? Send a message or use one of the direct project channels.',
    contactDirectTitle: 'Direct channels',
    contactFormTitle: 'Send us a message',
    projectEmail: 'support@cwd-rental.kg',
    projectWhatsapp: '+996 700 100 100',
    projectInstagram: '@cwd.rental.kg',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    officeHours: 'Support hours',
    officeHoursValue: '09:00 - 21:00, Bishkek time',
    yourName: 'Your name',
    yourEmail: 'Your email',
    yourMessage: 'Your message',
    messagePlaceholder: 'Tell us what you need: booking help, car listing, office details, or project feedback.',
    sendMessage: 'Send message',
    faqEyebrow: 'Help center',
    faqTitle: 'Frequently asked questions',
    faqLead: 'Clear answers about booking, partners, admin approval, offices, languages, and support.',
    tourismEyebrow: 'Kyrgyzstan travel guide',
    tourismTitle: 'Pick the season, then choose the road.',
    tourismLead: 'Lake beaches, red-rock canyons, hot springs, ski bases, and glacier trails are all reachable from the CWD office network. Plan the route first, then match the car to the road.',
    tourismTags: ['Lake', 'Gorge', 'Ski', 'Trek'],
    tourismFindCar: 'Find a trip car',
    tourismChooseOffice: 'Choose pickup city',
    tourismHeroImageAlt: 'Beautiful Issyk-Kul beach in Cholpon-Ata',
    tourismLoopLabel: 'Issyk-Kul beach loop',
    tourismLoopDuration: '3-7 days',
    tourismLoopText: 'Start in Bishkek, cross to the lake, follow the shore to Karakol, and add beaches, gorges, or hot springs when the weather looks good.',
    tourismSeasonEyebrow: 'Season ideas',
    tourismSeasonTitle: 'Travel by mood, not only by date.',
    tourismSeasonLead: 'Summer is for lake roads and yurt camps. Winter is for ski bases and shorter mountain days. Spring and autumn reward flexible travelers with quieter roads.',
    tourismSeasonCards: [
      {
        title: 'Issyk-Kul summer coast',
        time: 'June to September',
        text: 'Beach days around Cholpon-Ata, Bosteri, and Tamchy pair warm lake water with mountain views, water sports, sunset walks, and short cultural stops.',
        places: ['Cholpon-Ata beach', 'Bosteri resort strip', 'Tamchy quiet shore', 'Petroglyph open-air museum'],
      },
      {
        title: 'Gorges, lakes, and hiking',
        time: 'Mid-June to September',
        text: 'Karakol is the easy adventure base for Jeti-Oguz, Altyn-Arashan hot springs, Ala-Kul trekking, green valley routes, and southern road trips.',
        places: ['Jeti-Oguz rocks', 'Altyn-Arashan valley', 'Ala-Kul trek', 'Jyrgalan day hikes', 'Kara-Koy', 'Arslanbob', 'Sary-Chelek'],
      },
      {
        title: 'Skiing and alpine weekends',
        time: 'December to February',
        text: 'Winter changes the plan: stay near Bishkek or Karakol, choose snow-ready cars, check road conditions, and keep mountain days flexible.',
        places: ['Karakol ski base', 'Ala-Archa snow walks', 'Chunkurchak slopes', 'Suusamyr valley'],
      },
    ],
    tourismBestPlacesEyebrow: 'Best places for visitors',
    tourismBestPlacesTitle: 'A short list for the first route plan.',
    tourismBestPlaces: [
      { name: 'Issyk-Kul north shore', tag: 'Beaches', detail: 'Best for first-time lake trips, swimming, water activities, and lively summer evenings.' },
      { name: 'Issyk-Kul south shore', tag: 'Canyons', detail: 'Quieter villages, Fairy Tale Canyon, Barskoon waterfalls, yurt stays, and slower scenic roads.' },
      { name: 'Karakol and Jeti-Oguz', tag: 'Adventure', detail: 'A practical base for gorge walks, horse rides, hot springs, multi-day trekking, and mountain food stops.' },
      { name: 'Ala-Archa National Park', tag: 'Day trip', detail: 'The closest big-mountain escape from Bishkek, with easy valley walks and harder routes toward glacier views.' },
      { name: 'Song-Kul Lake', tag: 'Nomad life', detail: 'Summer yurt camps, horses, wide jailoo landscapes, cold nights, and huge open skies above 3,000 meters.' },
      { name: 'Alay Valley and Peak Lenin', tag: 'Alpinism', detail: 'Southern high-altitude scenery for serious trekkers, climbers, photographers, and Pamir road trips.' },
      { name: 'Kara-Koy', tag: 'South region', detail: 'A quieter southern stop for village scenery, regional roads, and flexible routes from Osh side.' },
      { name: 'Arslanbob', tag: 'Walnut forest', detail: 'A Jalal-Abad region favorite with waterfalls, homestays, horseback routes, and the famous walnut forest.' },
      { name: 'Sary-Chelek', tag: 'Nature reserve', detail: 'A peaceful lake-and-forest route for summer nature trips, photography, and slower southern travel.' },
    ],
    tourismDirections: 'Directions',
    tourismWikipedia: 'Wikipedia info',
    tourismBeforeRoad: 'Before the road',
    tourismNotesTitle: 'Smart tourism notes',
    tourismTripNotes: [
      'Reserve popular Issyk-Kul stays early for July and August.',
      'Carry warm layers even in summer; high valleys cool down fast after sunset.',
      'Choose a higher-clearance car for southern shore gorges, Song-Kul, and rough mountain roads.',
      'For alpinism or remote trekking, travel with local guides and check permits, weather, and rescue coverage.',
    ],
    tourismCarMatchTitle: 'Car match',
    tourismCarMatchText: 'City and north-shore lake routes fit most cars. South-shore canyons, jailoo roads, southern regional roads, and winter passes are better with higher clearance and confident tires.',
    tourismPhotoSources: 'Photo sources:',
    footerContactTitle: 'Project contacts',
  },
  ru: {
    language: 'Язык',
    english: 'Английский',
    russian: 'Русский',
    kyrgyz: 'Кыргызский',
    logo: 'CWD Аренда',
    logoAlt: 'Логотип CWD Rental автопарк Кыргызстана',
    tagline: 'Автопарк Кыргызстана',
    cars: 'Автомобили',
    offices: 'Офисы',
    contact: 'Контакты',
    faq: 'FAQ',
    admin: 'Админ',
    account: 'Кабинет',
    addCar: 'Добавить авто',
    login: 'Войти',
    register: 'Регистрация',
    logout: 'Выйти',
    heroTitle: 'Оставайтесь в пути с CWD и получите комфортный опыт аренды',
    heroImageAlt: 'Современный автомобиль на красивой туристической дороге',
    heroChips: ['Пляжи Иссык-Куля', 'Ущелья Тянь-Шаня', 'Летние и лыжные дороги'],
    heroLead: 'Премиальные авто для поездок к озеру, горных маршрутов, встреч в аэропорту и уверенных путешествий по Кыргызстану.',
    cwdMeaning: 'CWD - Comfort Wheels Drive: комфортные автомобили, надежные колеса и свобода ездить по Кыргызстану.',
    profilePhoto: 'Фото профиля',
    uploadProfilePhoto: 'Загрузить фото',
    changeProfilePhoto: 'Изменить фото',
    payment: 'Оплата',
    securePayment: 'Безопасная оплата',
    paymentTitle: 'Токенизированная оплата аренды',
    paymentLead: 'Данные карты остаются внутри слоя платежного провайдера. Backend получает только токен, ID аренды и сумму.',
    paymentProvider: 'Платежный провайдер',
    paymentMethod: 'Способ оплаты',
    card: 'Карта',
    digitalWallet: 'Электронный кошелек',
    tokenizedPaymentBox: 'Безопасный токен провайдера',
    tokenizedPaymentText: 'Демо-режим имитирует токенизацию Stripe или PayPal. Номер карты не хранится и не отправляется на backend.',
    paymentStatus: 'Статус оплаты',
    amountDue: 'К оплате',
    payNow: 'Оплатить',
    continueToPayment: 'Перейти к оплате',
    paymentSuccess: 'Оплата подтверждена через demo webhook. Аренда подтверждена.',
    paymentAlreadyPaid: 'Уже оплачено',
    paymentRentalNotFound: 'Аренда не найдена в вашем аккаунте.',
    refundReason: 'Причина возврата',
    refundReasonPlaceholder: 'Напишите, почему бронирование нужно отменить или вернуть оплату.',
    customerCancellationReason: 'Запрос клиента на отмену',
    refundCreated: 'Возврат создан, аренда отменена.',
    pickup: 'Офис получения',
    dropoff: 'Офис возврата',
    pickupDate: 'Дата получения',
    dropoffDate: 'Дата возврата',
    pickupTime: 'Время получения',
    dropoffTime: 'Время возврата',
    searchCars: 'Найти авто',
    liveFleet: 'Живой автопарк',
    carsForRent: 'Автомобили в аренду',
    approvedCarsAvailable: ({ count = 0 } = {}) => count === 1 ? '1 одобренное авто доступно' : `${count} одобренных авто доступно`,
    noCarsFound: 'Автомобили не найдены',
    noCarsText: 'Попробуйте изменить поиск или фильтры. Доступных авто много.',
    clearFilters: 'Очистить фильтры',
    clearAll: 'Очистить',
    filters: 'Фильтры',
    search: 'Поиск',
    pricePerDay: 'Цена за день',
    transmission: 'Коробка передач',
    fuel: 'Топливо',
    sortBy: 'Сортировка',
    lowToHigh: 'Цена: по возрастанию',
    highToLow: 'Цена: по убыванию',
    newestFirst: 'Сначала новые',
    carsFound: 'авто найдено',
    available: 'Доступно',
    seats: 'мест',
    viewDetails: 'Подробнее',
    backToCars: 'Назад к авто',
    verifiedFleet: 'Проверенный автопарк',
    readyToBook: 'Готовы бронировать?',
    bookNow: 'Забронировать',
    backendRentalHint: 'Выберите даты, и аренда будет создана через backend.',
    book: 'Бронь',
    confirmBooking: 'Подтвердить бронь',
    loginToBook: 'Войдите для брони',
    rentalCreated: 'Аренда создана',
    rentalCreatedText: 'Ваша бронь сохранена в Spring Boot backend.',
    viewMyRentals: 'Мои аренды',
    welcomeBack: 'С возвращением',
    signIn: 'Вход',
    email: 'Email',
    password: 'Пароль',
    signingIn: 'Входим...',
    noAccount: 'Нет аккаунта?',
    createPartnerAccount: 'Создать аккаунт партнера',
    createAccount: 'Создать аккаунт',
    creatingAccount: 'Создаем аккаунт...',
    fullName: 'Полное имя',
    phone: 'Телефон',
    confirmPassword: 'Подтвердите пароль',
    backToLogin: 'Назад ко входу',
    partnerAccess: 'Доступ партнера',
    officesNetwork: 'Сеть по Кыргызстану',
    officesLead: 'Выберите точку получения в аэропортах и городских офисах Бишкека, Оша, Иссык-Куля, Каракола и Джалал-Абада.',
    airportOffice: 'Офис в аэропорту',
    cityOffice: 'Городской офис',
    city: 'Город',
    code: 'Код',
    address: 'Адрес',
    workingHours: 'Время работы',
    availableServices: 'Доступные услуги',
    directions: 'Маршрут',
    officeServiceFallback: 'Эта услуга доступна в этом офисе. Свяжитесь с филиалом для точного времени и требований.',
    manageCars: 'Управление авто',
    adminFleet: 'Админ автопарк',
    partnerGarage: 'Гараж партнера',
    manageCarsAdminText: 'Одобряйте, отклоняйте, редактируйте или создавайте авто.',
    manageCarsPartnerText: 'Отправляйте авто на одобрение и управляйте объявлениями.',
    refresh: 'Обновить',
    closeForm: 'Закрыть форму',
    submitPartnerCar: 'Добавить авто партнера',
    createApprovedCar: 'Создать одобренное авто',
    editCar: 'Редактировать авто',
    brand: 'Марка',
    model: 'Модель',
    year: 'Год',
    vin: 'VIN, 11-17 символов',
    description: 'Описание',
    carImages: 'До 3 фото авто с вашего устройства',
    image: 'Фото',
    chooseFile: 'Выберите файл',
    noFileChosen: 'Файл не выбран',
    removeImage: 'Удалить фото',
    updateCar: 'Обновить авто',
    createCar: 'Создать авто',
    sendForApproval: 'Отправить на одобрение',
    cancel: 'Отмена',
    delete: 'Удалить',
    approve: 'Одобрить',
    reject: 'Отклонить',
    security: 'Безопасность',
    backendUsers: 'Пользователи',
    adminWorkspace: 'Рабочая зона админа',
    controlCenter: 'Центр управления',
    adminControl: 'Админ-контроль',
    rentalHistory: 'История аренд',
    rentals: 'Аренды',
    users: 'Пользователи',
    user: 'Пользователь',
    car: 'Авто',
    dates: 'Даты',
    total: 'Итого',
    allRoles: 'Все роли',
    allProviders: 'Все провайдеры',
    allStatuses: 'Все статусы',
    active: 'Активен',
    banned: 'Забанен',
    ban: 'Бан',
    unban: 'Разбанить',
    reason: 'Причина',
    actions: 'Действия',
    banUser: 'Забанить пользователя',
    bannedReason: 'Причина бана',
    writeBanReason: 'Напишите причину бана пользователя...',
    profile: 'Профиль',
    myRentals: 'Мои аренды',
    partnerDashboard: 'Кабинет партнера',
    myAccount: 'Мой кабинет',
    backendRentals: 'Аренды',
    noRentals: 'Аренд пока нет. Выберите авто и создайте первую бронь.',
    totalSpend: 'Общая сумма',
    provider: 'Провайдер',
    role: 'Роль',
    status: 'Статус',
    location: 'Локация',
    auto: 'Автомат',
    manual: 'Механика',
    gas: 'Бензин',
    diesel: 'Дизель',
    hybrid: 'Гибрид',
    bookingSummary: 'Итоги бронирования',
    bookingDetails: 'Детали брони',
    availableCars: 'Доступные авто',
    days: 'Дни',
    loginSideTitle: 'Арендуйте, добавляйте, одобряйте и управляйте авто в одном удобном кабинете.',
    loginSideText: 'Управляйте арендами и одобренным автопарком в чистом и безопасном пространстве.',
    oauthLoginFailed: 'Ошибка входа через OAuth',
    oauthNotConfigured: 'Вход через Google еще не настроен. Проверьте GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET и redirect URI в Google.',
    connectingGoogle: 'Подключаем Google...',
    passwordPlaceholder: 'Ваш пароль',
    createYourAccount: 'Создайте аккаунт',
    passwordsDoNotMatch: 'Пароли не совпадают',
    registrationFailed: 'Регистрация не удалась',
    loading: 'Загрузка...',
    loadingCars: 'Загрузка авто...',
    loadingRentals: 'Загрузка аренд...',
    loadingUsers: 'Загрузка пользователей...',
    noCarsYet: 'Авто пока нет. Добавьте первое авто.',
    noBackendRentals: 'Аренд в backend пока нет.',
    noUsersMatch: 'Нет пользователей по выбранным фильтрам.',
    carUpdated: 'Авто обновлено. Изменения партнера снова отправлены на одобрение.',
    adminCarCreated: 'Авто админа создано и сразу одобрено.',
    carSubmitted: 'Авто отправлено админу на одобрение.',
    carDeleted: 'Авто удалено.',
    deleteCarConfirm: 'Удалить это авто из backend?',
    deleteUserConfirm: ({ email }) => `Удалить пользователя ${email}? Это мягкое удаление в базе данных.`,
    banReasonRequired: 'Причина бана обязательна',
    banning: 'Баним...',
    brandModelVinRequired: 'Марка, модель и VIN обязательны',
    vinMinLength: 'VIN должен содержать минимум 11 символов',
    priceGreaterThanZero: 'Цена должна быть больше нуля',
    edit: 'Редактировать',
    perDay: 'в день',
    backendRental: 'Backend аренда',
    rentalDays: ({ days }) => `${days} дней аренды`,
    creatingRental: 'Создаем аренду...',
    activeRentals: 'Активные аренды',
    notSet: 'Не указано',
    hi: 'Здравствуйте',
    id: 'ID',
    searchUsers: 'Поиск по ID, имени или email',
    complete: 'Завершить',
    findMyRental: 'Найти мою аренду',
    cancelRental: 'Отменить аренду',
    rentalSupport: 'Поддержка аренды',
    rentalId: 'ID аренды',
    enterRentalId: 'Введите ID аренды',
    checking: 'Проверяем...',
    cancelRentalLead: 'Админы могут отменять напрямую. Партнеры могут проверить аренду и связаться с поддержкой.',
    rentalCancelled: 'Аренда отменена в backend.',
    rentalNotFound: 'Аренда не найдена в вашем аккаунте.',
    rentalFoundContactSupport: 'Ваша аренда найдена. Отмена через backend доступна только админу, поэтому свяжитесь с поддержкой или админом.',
    dashboardLead: 'Отслеживайте аренды, управляйте партнерскими авто и держите каждую поездку в порядке из одного стильного кабинета.',
    verifiedPartner: 'Проверенный партнерский кабинет',
    profileDetails: 'Детали профиля',
    quickActions: 'Быстрые действия',
    accountSecurity: 'Безопасность аккаунта',
    accountSecurityText: 'Аккаунт использует backend-аутентификацию, провайдера входа и доступ по ролям.',
    planTrip: 'Запланировать поездку',
    exploreOffices: 'Открыть офисы',
    requestSupport: 'Запросить поддержку',
    cancelHelp: 'Помощь с отменой',
    recentActivity: 'Последняя активность',
    noActivity: 'Активности по арендам пока нет. Выберите авто, и первая поездка появится здесь.',
    supportWorkflow: 'Процесс поддержки',
    cancelStepOne: 'Введите ID аренды',
    cancelStepTwo: 'Мы проверяем владельца и статус',
    cancelStepThree: 'Админ или поддержка завершает отмену',
    saferCancelTitle: 'Безопасная отмена и понятная проверка',
    saferCancelText: 'Партнеры могут проверить свою аренду перед действием поддержки. Админы отменяют напрямую через backend status endpoint.',
    directSupport: 'Прямая поддержка',
    adminDashboardLead: 'Проверяйте автопарк, статусы аренд, пользователей и безопасность платформы из одного командного центра.',
    verifiedAdmin: 'Проверенный админ-кабинет',
    adminOverview: 'Обзор операций',
    fleetControl: 'Контроль автопарка',
    fleetControlText: 'Одобряйте авто партнеров, создавайте официальные авто и держите объявления надежными.',
    rentalControlText: 'Завершайте или отменяйте backend-аренды и отслеживайте историю поездок.',
    userControlText: 'Фильтруйте пользователей, баньте рискованные аккаунты с причиной и держите доступ чистым.',
    commandShortcuts: 'Быстрые команды',
    reviewCars: 'Проверить авто',
    reviewRentals: 'Проверить аренды',
    reviewUsers: 'Проверить пользователей',
    platformHealth: 'Состояние платформы',
    platformHealthText: 'Backend-данные подключены через защищенные admin API с доступом по ролям.',
    name: 'Имя',
    message: 'Сообщение',
    send: 'Отправить',
    messageSent: 'Сообщение отправлено! (Демо)',
    contactSupportDetails: 'Для подробностей свяжитесь с нашей поддержкой.',
    pageNotFound: 'Страница не найдена',
    pageNotFoundText: 'К сожалению, запрошенная страница не существует.',
    home: 'Главная',
    corporate: 'Корпоративным клиентам',
    modify: 'Изменить бронь',
    cancelBookingFooter: 'Отменить бронь',
    help: 'Помощь',
    about: 'О нас',
    feedback: 'Обратная связь',
    other: 'Другое',
    destinations: 'Направления',
    fleet: 'Автопарк',
    policies: 'Правила',
    privacy: 'Конфиденциальность',
    legal: 'Юридическая информация',
    terms: 'Условия',
    copyright: '© 2026 CWD Rental. Все права защищены.',
    faqItems: [
      { q: 'Как забронировать авто?', a: 'Выберите даты получения и возврата, откройте карточку автомобиля, проверьте детали и подтвердите бронь. Запрос сохраняется через Spring Boot backend.' },
      { q: 'Могут ли партнеры добавлять свои автомобили?', a: 'Да. Партнеры могут отправлять авто с типом топлива, коробкой передач, ценой, VIN, описанием и до трех локальных изображений. Перед публикацией нужно одобрение админа.' },
      { q: 'Как работает одобрение админом?', a: 'Админы проверяют отправленные автомобили, одобряют надежные объявления, отклоняют некорректные данные, управляют арендами и контролируют доступ пользователей.' },
      { q: 'Какие способы оплаты доступны?', a: 'Оплата и депозит подтверждаются в офисе при получении автомобиля. Сейчас webapp сфокусирован на бронировании, аккаунтах, автопарке и админ-панели.' },
      { q: 'Можно ли изменить или отменить бронь?', a: 'Партнеры могут проверить аренду в личном кабинете. Админы могут отменять или завершать аренды в backend dashboard, а поддержка помогает с изменением дат.' },
      { q: 'Какие языки поддерживаются?', a: 'Интерфейс поддерживает английский, русский и кыргызский. Используйте вертикальный переключатель языка в хедере.' },
      { q: 'Какие офисы доступны?', a: 'В проекте есть аэропортовые и городские офисы: Манас, Ош, Бишкек, Иссык-Куль, Каракол и Джалал-Абад с деталями для туристических маршрутов.' },
    ],
    aboutEyebrow: 'Создано студентами МУА в 2026',
    aboutTitle: 'Платформа аренды авто для туризма в Кыргызстане',
    aboutLead: 'Этa веб-платформа была создана студентами Международного Университета Ала-Тоо в 2026 году, чтобы поддержать туризм, сделать поездки внутри страны комфортнее и соединить гостей с удобной локальной мобильностью.',
    aboutStoryTitle: 'Студенческий проект с реальной туристической миссией',
    aboutStoryText: 'CWD Rental объединяет React frontend и Spring Boot backend, показывая, как современный университетский проект может решать практическую задачу туризма: бронирование надежных авто, поиск офисов и безопасная публикация машин партнерами.',
    aboutTourismTitle: 'Создано для комфортных поездок по стране',
    aboutTourismText: 'Опыт сфокусирован на маршрутах Кыргызстана: встреча в аэропорту, городские офисы, горные поездки, путешествия к озеру, региональные дороги и понятная коммуникация перед началом пути.',
    aboutFleetTitle: 'Автопарк, партнеры и админ-контроль в одной системе',
    aboutFleetText: 'Партнеры добавляют авто с изображениями и деталями, а админы одобряют объявления, управляют арендами, банят небезопасных пользователей с причиной и поддерживают порядок.',
    aboutStats: [
      { value: '2026', label: 'год запуска проекта' },
      { value: '3', label: 'языка интерфейса' },
      { value: '7', label: 'туристических офисов' },
      { value: '24/7', label: 'поддержка аэропортов' },
    ],
    aboutHighlights: [
      'Создано студентами Международного Университета Ала-Тоо',
      'Поддерживает внутренний туризм и региональные поездки',
      'React, Spring Boot, JWT, OAuth2 и PostgreSQL',
      'Партнерские и админские функции подключены к backend',
    ],
    contactEyebrow: 'Контакты проекта',
    contactTitle: 'Свяжитесь с командой CWD Rental',
    contactLead: 'Есть вопросы про автомобили, офисы, партнерские объявления, админ-поддержку или идею проекта? Отправьте сообщение или используйте прямые каналы связи.',
    contactDirectTitle: 'Прямые каналы',
    contactFormTitle: 'Отправьте сообщение',
    projectEmail: 'support@cwd-rental.kg',
    projectWhatsapp: '+996 700 100 100',
    projectInstagram: '@cwd.rental.kg',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    officeHours: 'Время поддержки',
    officeHoursValue: '09:00 - 21:00, время Бишкека',
    yourName: 'Ваше имя',
    yourEmail: 'Ваш email',
    yourMessage: 'Ваше сообщение',
    messagePlaceholder: 'Напишите, что вам нужно: помощь с бронью, добавление авто, детали офиса или отзыв о проекте.',
    sendMessage: 'Отправить сообщение',
    faqEyebrow: 'Центр помощи',
    faqTitle: 'Частые вопросы',
    faqLead: 'Понятные ответы про бронирование, партнеров, одобрение админом, офисы, языки и поддержку.',
    tourismEyebrow: 'Туристический гид по Кыргызстану',
    tourismTitle: 'Выберите сезон, затем дорогу.',
    tourismLead: 'Пляжи озера, красные каньоны, горячие источники, лыжные базы и ледниковые тропы доступны через сеть офисов CWD. Сначала спланируйте маршрут, затем подберите автомобиль под дорогу.',
    tourismTags: ['Озеро', 'Ущелье', 'Лыжи', 'Треккинг'],
    tourismFindCar: 'Найти авто для поездки',
    tourismChooseOffice: 'Выбрать город получения',
    tourismHeroImageAlt: 'Красивый пляж Иссык-Куля в Чолпон-Ате',
    tourismLoopLabel: 'Пляжный круг Иссык-Куля',
    tourismLoopDuration: '3-7 дней',
    tourismLoopText: 'Начните в Бишкеке, доезжайте до озера, двигайтесь по берегу к Караколу и добавляйте пляжи, ущелья или горячие источники по погоде.',
    tourismSeasonEyebrow: 'Идеи по сезонам',
    tourismSeasonTitle: 'Путешествуйте по настроению, а не только по датам.',
    tourismSeasonLead: 'Лето подходит для озерных дорог и юрточных лагерей. Зима подходит для лыжных баз и коротких горных дней. Весна и осень дают более спокойные дороги.',
    tourismSeasonCards: [
      {
        title: 'Летний берег Иссык-Куля',
        time: 'Июнь - сентябрь',
        text: 'Пляжи Чолпон-Аты, Бостери и Тамчы объединяют теплую воду, виды на горы, водные развлечения, закаты и короткие культурные остановки.',
        places: ['Пляж Чолпон-Аты', 'Курортная зона Бостери', 'Тихий берег Тамчы', 'Музей петроглифов'],
      },
      {
        title: 'Ущелья, озера и походы',
        time: 'С середины июня до сентября',
        text: 'Каракол удобен для Джети-Огуза, горячих источников Алтын-Арашана, треккинга к Ала-Кулю, зеленых долин и южных маршрутов.',
        places: ['Скалы Джети-Огуз', 'Долина Алтын-Арашан', 'Трек к Ала-Кулю', 'Походы в Жыргалане', 'Кара-Кой', 'Арсланбоб', 'Сары-Челек'],
      },
      {
        title: 'Лыжи и альпийские выходные',
        time: 'Декабрь - февраль',
        text: 'Зимой план меняется: останавливайтесь рядом с Бишкеком или Караколом, выбирайте авто для снега, проверяйте дороги и оставляйте запас по времени.',
        places: ['Горнолыжная база Каракол', 'Зимние прогулки в Ала-Арче', 'Склоны Чункурчака', 'Суусамырская долина'],
      },
    ],
    tourismBestPlacesEyebrow: 'Лучшие места для гостей',
    tourismBestPlacesTitle: 'Короткий список для первого маршрута.',
    tourismBestPlaces: [
      { name: 'Северный берег Иссык-Куля', tag: 'Пляжи', detail: 'Лучший вариант для первой поездки к озеру, купания, водных развлечений и живых летних вечеров.' },
      { name: 'Южный берег Иссык-Куля', tag: 'Каньоны', detail: 'Более тихие села, каньон Сказка, водопады Барскоон, юрточные остановки и живописные дороги.' },
      { name: 'Каракол и Джети-Огуз', tag: 'Приключения', detail: 'Удобная база для ущелий, конных прогулок, горячих источников, треккинга и горной кухни.' },
      { name: 'Национальный парк Ала-Арча', tag: 'День из Бишкека', detail: 'Самый близкий горный выезд из Бишкека с простыми прогулками и сложными маршрутами к ледникам.' },
      { name: 'Озеро Сон-Куль', tag: 'Кочевая жизнь', detail: 'Летние юрточные лагеря, лошади, широкие жайлоо, холодные ночи и огромное небо выше 3 000 метров.' },
      { name: 'Алайская долина и пик Ленина', tag: 'Альпинизм', detail: 'Южные высокогорные пейзажи для опытных туристов, альпинистов, фотографов и маршрутов к Памиру.' },
      { name: 'Кара-Кой', tag: 'Южный регион', detail: 'Тихая южная остановка для сельских пейзажей, региональных дорог и гибких маршрутов со стороны Оша.' },
      { name: 'Арсланбоб', tag: 'Ореховый лес', detail: 'Любимое место Джалал-Абадской области с водопадами, гостевыми домами, конными маршрутами и ореховым лесом.' },
      { name: 'Сары-Челек', tag: 'Заповедник', detail: 'Спокойный маршрут к озеру и лесам для летней природы, фотографии и медленного путешествия по югу.' },
    ],
    tourismDirections: 'Маршрут',
    tourismWikipedia: 'Инфо Wikipedia',
    tourismBeforeRoad: 'Перед дорогой',
    tourismNotesTitle: 'Полезные заметки для туристов',
    tourismTripNotes: [
      'Популярные места на Иссык-Куле лучше бронировать заранее на июль и август.',
      'Берите теплые вещи даже летом: в высоких долинах быстро холодает после заката.',
      'Для южного берега, ущелий, Сон-Куля и горных дорог лучше выбирать авто с высоким клиренсом.',
      'Для альпинизма и удаленного треккинга пользуйтесь местными гидами и проверяйте разрешения, погоду и страховку.',
    ],
    tourismCarMatchTitle: 'Подбор авто',
    tourismCarMatchText: 'Городские и северные маршруты к озеру подходят большинству авто. Южный берег, каньоны, жайлоо, южные региональные дороги и зимние перевалы лучше проходить на машине с высоким клиренсом и уверенными шинами.',
    tourismPhotoSources: 'Источники фото:',
    footerContactTitle: 'Контакты проекта',
  },
  kg: {
    language: 'Тил',
    english: 'Англисче',
    russian: 'Орусча',
    kyrgyz: 'Кыргызча',
    logo: 'CWD Ижара',
    logoAlt: 'CWD Rental Кыргызстан автопаркы логотиби',
    tagline: 'Кыргызстан автопаркы',
    cars: 'Унаалар',
    offices: 'Офистер',
    contact: 'Байланыш',
    faq: 'Суроолор',
    admin: 'Админ',
    account: 'Кабинет',
    addCar: 'Унаа кошуу',
    login: 'Кирүү',
    register: 'Катталуу',
    logout: 'Чыгуу',
    heroTitle: 'CWD менен жолдо болуп, ыңгайлуу ижара тажрыйбасын алыңыз',
    heroImageAlt: 'Кооз туристтик жолдогу заманбап унаа',
    heroChips: ['Ысык-Көл пляждары', 'Тянь-Шань капчыгайлары', 'Жайкы жана лыжа жолдору'],
    heroLead: 'Көлгө, тоо маршруттарына, аэропорттон тосуп алууга жана Кыргызстан боюнча ишенимдүү саякатка премиум унаалар.',
    cwdMeaning: 'CWD - Comfort Wheels Drive: ыңгайлуу унаалар, ишенимдүү дөңгөлөктөр жана Кыргызстанды эркин кыдыруу.',
    profilePhoto: 'Профиль сүрөтү',
    uploadProfilePhoto: 'Сүрөт жүктөө',
    changeProfilePhoto: 'Сүрөттү өзгөртүү',
    payment: 'Төлөм',
    securePayment: 'Коопсуз төлөм',
    paymentTitle: 'Токен аркылуу ижара төлөмү',
    paymentLead: 'Карта маалыматтары төлөм провайдеринин ичинде калат. Backend токенди, ижара IDсин жана сумманы гана алат.',
    paymentProvider: 'Төлөм провайдери',
    paymentMethod: 'Төлөм ыкмасы',
    card: 'Карта',
    digitalWallet: 'Электрондук капчык',
    tokenizedPaymentBox: 'Провайдердин коопсуз токени',
    tokenizedPaymentText: 'Демо режим Stripe же PayPal токенизациясын окшоштурат. Карта номери сакталбайт жана backendке жөнөтүлбөйт.',
    paymentStatus: 'Төлөм статусу',
    amountDue: 'Төлөнө турган сумма',
    payNow: 'Төлөө',
    continueToPayment: 'Төлөмгө өтүү',
    paymentSuccess: 'Төлөм demo webhook аркылуу тастыкталды. Ижара ырасталды.',
    paymentAlreadyPaid: 'Төлөнгөн',
    paymentRentalNotFound: 'Ижара аккаунтуңуздан табылган жок.',
    refundReason: 'Кайтаруу себеби',
    refundReasonPlaceholder: 'Бронду эмне үчүн жокко чыгаруу же төлөмдү кайтаруу керек экенин жазыңыз.',
    customerCancellationReason: 'Кардардын жокко чыгаруу суроосу',
    refundCreated: 'Кайтаруу түзүлдү жана ижара жокко чыгарылды.',
    pickup: 'Алуу офиси',
    dropoff: 'Кайтаруу офиси',
    pickupDate: 'Алуу күнү',
    dropoffDate: 'Кайтаруу күнү',
    pickupTime: 'Алуу убактысы',
    dropoffTime: 'Кайтаруу убактысы',
    searchCars: 'Унаа издөө',
    liveFleet: 'Жандуу автопарк',
    carsForRent: 'Ижарага унаалар',
    approvedCarsAvailable: ({ count = 0 } = {}) => count === 1 ? '1 бекитилген унаа жеткиликтүү' : `${count} бекитилген унаа жеткиликтүү`,
    noCarsFound: 'Унаалар табылган жок',
    noCarsText: 'Издөөнү же фильтрлерди өзгөртүп көрүңүз. Жеткиликтүү унаалар көп.',
    clearFilters: 'Фильтрлерди тазалоо',
    clearAll: 'Тазалоо',
    filters: 'Фильтрлер',
    search: 'Издөө',
    pricePerDay: 'Күндүк баа',
    transmission: 'Коробка',
    fuel: 'Күйүүчү май',
    sortBy: 'Иреттөө',
    lowToHigh: 'Баа: төмөндөн жогору',
    highToLow: 'Баа: жогорудан төмөн',
    newestFirst: 'Жаңылары биринчи',
    carsFound: 'унаа табылды',
    available: 'Жеткиликтүү',
    seats: 'орун',
    viewDetails: 'Толук маалымат',
    backToCars: 'Унааларга кайтуу',
    verifiedFleet: 'Текшерилген автопарк',
    readyToBook: 'Брондоого даярсызбы?',
    bookNow: 'Азыр брондоо',
    backendRentalHint: 'Күндөрдү тандаңыз, ижара backend аркылуу түзүлөт.',
    book: 'Брондоо',
    confirmBooking: 'Бронду ырастоо',
    loginToBook: 'Брондоо үчүн кириңиз',
    rentalCreated: 'Ижара түзүлдү',
    rentalCreatedText: 'Бронуңуз Spring Boot backend ичинде сакталды.',
    viewMyRentals: 'Менин ижараларым',
    welcomeBack: 'Кайра келиңиз',
    signIn: 'Кирүү',
    email: 'Email',
    password: 'Сырсөз',
    signingIn: 'Кирип жатат...',
    noAccount: 'Аккаунтуңуз жокпу?',
    createPartnerAccount: 'Партнер аккаунтун түзүү',
    createAccount: 'Аккаунт түзүү',
    creatingAccount: 'Аккаунт түзүлүүдө...',
    fullName: 'Толук аты-жөнү',
    phone: 'Телефон',
    confirmPassword: 'Сырсөздү ырастоо',
    backToLogin: 'Кирүүгө кайтуу',
    partnerAccess: 'Партнер мүмкүнчүлүгү',
    officesNetwork: 'Кыргызстан боюнча тармак',
    officesLead: 'Бишкек, Ош, Ысык-Көл, Каракол жана Жалал-Абаддагы аэропорт жана шаардык офистерден алуу жерин тандаңыз.',
    airportOffice: 'Аэропорт офиси',
    cityOffice: 'Шаардык офис',
    city: 'Шаар',
    code: 'Код',
    address: 'Дарек',
    workingHours: 'Иштөө убактысы',
    availableServices: 'Жеткиликтүү кызматтар',
    directions: 'Маршрут',
    officeServiceFallback: 'Бул кызмат ушул офисте жеткиликтүү. Так убакыт жана талаптар үчүн филиал менен байланышыңыз.',
    manageCars: 'Унааларды башкаруу',
    adminFleet: 'Админ автопарк',
    partnerGarage: 'Партнер гаражы',
    manageCarsAdminText: 'Унааларды бекитиңиз, четке кагыңыз, түзөтүңүз же түзүңүз.',
    manageCarsPartnerText: 'Унааларды бекитүүгө жөнөтүп, жарыяларыңызды башкарыңыз.',
    refresh: 'Жаңылоо',
    closeForm: 'Форманы жабуу',
    submitPartnerCar: 'Партнер унаасын кошуу',
    createApprovedCar: 'Бекитилген унаа түзүү',
    editCar: 'Унааны түзөтүү',
    brand: 'Марка',
    model: 'Модель',
    year: 'Жыл',
    vin: 'VIN, 11-17 белги',
    description: 'Сүрөттөмө',
    carImages: 'Түзмөгүңүздөн 3кө чейин унаа сүрөтү',
    image: 'Сүрөт',
    chooseFile: 'Файл тандоо',
    noFileChosen: 'Файл тандалган жок',
    removeImage: 'Сүрөттү өчүрүү',
    updateCar: 'Унааны жаңыртуу',
    createCar: 'Унаа түзүү',
    sendForApproval: 'Бекитүүгө жөнөтүү',
    cancel: 'Жокко чыгаруу',
    delete: 'Өчүрүү',
    approve: 'Бекитүү',
    reject: 'Четке кагуу',
    security: 'Коопсуздук',
    backendUsers: 'Жалпы колдонуучулар',
    adminWorkspace: 'Админ иш аймагы',
    controlCenter: 'Башкаруу борбору',
    adminControl: 'Админ көзөмөлү',
    rentalHistory: 'Ижара тарыхы',
    rentals: 'Ижаралар',
    users: 'Колдонуучулар',
    user: 'Колдонуучу',
    car: 'Унаа',
    dates: 'Күндөр',
    total: 'Жалпы',
    allRoles: 'Бардык ролдор',
    allProviders: 'Бардык провайдерлер',
    allStatuses: 'Бардык статустар',
    active: 'Активдүү',
    banned: 'Бан',
    ban: 'Бан кылуу',
    unban: 'Бандан чыгаруу',
    reason: 'Себеп',
    actions: 'Аракеттер',
    banUser: 'Колдонуучуну бан кылуу',
    bannedReason: 'Бандын себеби',
    writeBanReason: 'Колдонуучуну эмне үчүн бан кылганыңызды жазыңыз...',
    profile: 'Профиль',
    myRentals: 'Менин ижараларым',
    partnerDashboard: 'Партнер кабинети',
    myAccount: 'Менин кабинет',
    backendRentals: 'Backend ижаралары',
    noRentals: 'Азырынча ижара жок. Биринчи бронду түзүү үчүн унаа тандаңыз.',
    totalSpend: 'Жалпы сумма',
    provider: 'Провайдер',
    role: 'Роль',
    status: 'Статус',
    location: 'Жайгашкан жер',
    auto: 'Автомат',
    manual: 'Механика',
    gas: 'Бензин',
    diesel: 'Дизель',
    hybrid: 'Гибрид',
    bookingSummary: 'Брон жыйынтыгы',
    bookingDetails: 'Брон маалыматы',
    availableCars: 'Жеткиликтүү унаалар',
    days: 'Күндөр',
    loginSideTitle: 'Унааны ижарага алыңыз, кошуңуз, бекитиңиз жана баарын бир ыңгайлуу кабинеттен башкарыңыз.',
    loginSideText: 'Ижараларыңызды жана бекитилген автопаркыңызды таза, коопсуз мейкиндикте башкарыңыз.',
    oauthLoginFailed: 'OAuth аркылуу кирүү ишке ашкан жок',
    oauthNotConfigured: 'Google аркылуу кирүү азырынча толук жөндөлө элек. GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET жана Google redirect URI текшериңиз.',
    connectingGoogle: 'Google менен туташууда...',
    passwordPlaceholder: 'Сырсөзүңүз',
    createYourAccount: 'Аккаунт түзүңүз',
    passwordsDoNotMatch: 'Сырсөздөр дал келбейт',
    registrationFailed: 'Катталуу ишке ашкан жок',
    loading: 'Жүктөлүүдө...',
    loadingCars: 'Унаалар жүктөлүүдө...',
    loadingRentals: 'Ижаралар жүктөлүүдө...',
    loadingUsers: 'Колдонуучулар жүктөлүүдө...',
    noCarsYet: 'Азырынча унаа жок. Биринчи унааны кошуңуз.',
    noBackendRentals: 'Backend ичинде ижаралар азырынча жок.',
    noUsersMatch: 'Тандалган фильтрлер боюнча колдонуучу жок.',
    carUpdated: 'Унаа жаңыртылды. Партнердин өзгөртүүсү кайра бекитүүгө жөнөтүлөт.',
    adminCarCreated: 'Админ унаасы түзүлүп, дароо бекитилди.',
    carSubmitted: 'Унаа админдин бекитүүсүнө жөнөтүлдү.',
    carDeleted: 'Унаа өчүрүлдү.',
    deleteCarConfirm: 'Бул унааны backend ичинен өчүрөсүзбү?',
    deleteUserConfirm: ({ email }) => `${email} колдонуучусун өчүрөсүзбү? Бул база ичинде жумшак өчүрүү болот.`,
    banReasonRequired: 'Бандын себеби милдеттүү',
    banning: 'Бан коюлууда...',
    brandModelVinRequired: 'Марка, модель жана VIN милдеттүү',
    vinMinLength: 'VIN кеминде 11 белгиден турушу керек',
    priceGreaterThanZero: 'Баасы нөлдөн жогору болушу керек',
    edit: 'Түзөтүү',
    perDay: 'күнүнө',
    backendRental: 'Ижаралар',
    rentalDays: ({ days }) => `${days} күн ижара`,
    creatingRental: 'Ижара түзүлүүдө...',
    activeRentals: 'Активдүү ижаралар',
    notSet: 'Көрсөтүлгөн эмес',
    hi: 'Салам',
    id: 'ID',
    searchUsers: 'ID, аты же email боюнча издөө',
    complete: 'Аяктоо',
    findMyRental: 'Ижарамды табуу',
    cancelRental: 'Ижараны жокко чыгаруу',
    rentalSupport: 'Ижара колдоосу',
    rentalId: 'Ижара ID',
    enterRentalId: 'Ижара ID киргизиңиз',
    checking: 'Текшерилүүдө...',
    cancelRentalLead: 'Админдер түз жокко чыгара алат. Партнерлер ижараны текшерип, колдоого кайрыла алат.',
    rentalCancelled: 'Ижара backend ичинде жокко чыгарылды.',
    rentalNotFound: 'Ижара аккаунтуңуздан табылган жок.',
    rentalFoundContactSupport: 'Ижараңыз табылды. Backend аркылуу жокко чыгаруу админге гана жеткиликтүү, ошондуктан колдоо же админ менен байланышыңыз.',
    dashboardLead: 'Ижараларды көзөмөлдөп, партнер унааларыңызды башкарып, ар бир сапарды бир кооз кабинетте иреттеңиз.',
    verifiedPartner: 'Текшерилген партнер кабинети',
    profileDetails: 'Профиль маалыматтары',
    quickActions: 'Тез аракеттер',
    accountSecurity: 'Аккаунт коопсуздугу',
    accountSecurityText: 'Аккаунт backend authentication, кирүү провайдери жана ролдук жеткиликтүүлүк менен иштейт.',
    planTrip: 'Сапар пландоо',
    exploreOffices: 'Офистерди көрүү',
    requestSupport: 'Колдоого кайрылуу',
    cancelHelp: 'Жокко чыгаруу жардамы',
    recentActivity: 'Акыркы активдүүлүк',
    noActivity: 'Ижара активдүүлүгү азырынча жок. Унаа тандасаңыз, биринчи сапар бул жерде чыгат.',
    supportWorkflow: 'Колдоо процесси',
    cancelStepOne: 'Ижара ID киргизиңиз',
    cancelStepTwo: 'Биз ээликти жана статусту текшеребиз',
    cancelStepThree: 'Админ же колдоо жокко чыгарууну аяктайт',
    saferCancelTitle: 'Коопсуз жокко чыгаруу жана так текшерүү',
    saferCancelText: 'Партнерлер колдоо аракетине чейин ижарасын текшере алат. Админдер backend status endpoint аркылуу түз жокко чыгарат.',
    directSupport: 'Түз колдоо',
    adminDashboardLead: 'Автопаркты, ижара статусун, колдонуучуларды жана платформа коопсуздугун бир командалык борбордон текшериңиз.',
    verifiedAdmin: 'Текшерилген админ кабинети',
    adminOverview: 'Операциялар обзору',
    fleetControl: 'Автопарк көзөмөлү',
    fleetControlText: 'Партнер унааларын бекитиңиз, расмий унааларды түзүңүз жана жарыяларды ишенимдүү кармаңыз.',
    rentalControlText: 'Backend ижараларын аяктап же жокко чыгарып, сапар тарыхын көзөмөлдөңүз.',
    userControlText: 'Колдонуучуларды фильтрлеп, кооптуу аккаунттарды себеп менен бан кылып, жеткиликтүүлүктү таза кармаңыз.',
    commandShortcuts: 'Тез командалар',
    reviewCars: 'Унааларды текшерүү',
    reviewRentals: 'Ижараларды текшерүү',
    reviewUsers: 'Колдонуучуларды текшерүү',
    platformHealth: 'Платформа абалы',
    platformHealthText: 'Backend маалыматтары ролдук жеткиликтүүлүгү бар корголгон admin API аркылуу туташкан.',
    name: 'Аты',
    message: 'Билдирүү',
    send: 'Жөнөтүү',
    messageSent: 'Билдирүү жөнөтүлдү! (Демо)',
    contactSupportDetails: 'Көбүрөөк маалымат үчүн колдоо командабызга кайрылыңыз.',
    pageNotFound: 'Барак табылган жок',
    pageNotFoundText: 'Кечиресиз, суралган барак жок.',
    home: 'Башкы бет',
    corporate: 'Корпоративдик кардарлар',
    modify: 'Бронду өзгөртүү',
    cancelBookingFooter: 'Бронду жокко чыгаруу',
    help: 'Жардам',
    about: 'Биз жөнүндө',
    feedback: 'Пикир',
    other: 'Башка',
    destinations: 'Багыттар',
    fleet: 'Автопарк',
    policies: 'Эрежелер',
    privacy: 'Купуялык',
    legal: 'Юридикалык маалымат',
    terms: 'Шарттар',
    copyright: '© 2026 CWD Rental. Бардык укуктар корголгон.',
    faqItems: [
      { q: 'Унааны кантип брондойм?', a: 'Алуу жана кайтаруу күндөрүн тандап, унаа карточкасын ачып, маалыматты текшерип, бронду ырастаңыз. Сурам Spring Boot backend аркылуу сакталат.' },
      { q: 'Партнерлер өз унаасын кошо алабы?', a: 'Ооба. Партнерлер күйүүчү май, коробка, баа, VIN, сүрөттөмө жана үчкө чейин локалдык сүрөт менен унаа жөнөтө алат. Коомдук автопаркка чыгышы үчүн админ бекитиши керек.' },
      { q: 'Админ бекитүүсү кантип иштейт?', a: 'Админдер жөнөтүлгөн унааларды текшерет, ишенимдүү жарыяларды бекитет, туура эмес маалыматты четке кагат, ижараларды башкарат жана колдонуучу жеткиликтүүлүгүн көзөмөлдөйт.' },
      { q: 'Кандай төлөм ыкмалары бар?', a: 'Төлөм жана депозит шарттары унааны алган учурда офисте такталат. Азыр webapp брондоо, аккаунт, автопарк жана админ функцияларына багытталган.' },
      { q: 'Бронду өзгөртүп же жокко чыгарса болобу?', a: 'Партнерлер ижараны жеке кабинеттен текшере алат. Админдер backend dashboard ичинде ижараны жокко чыгарып же аяктата алат, колдоо даталарды өзгөртүүгө жардам берет.' },
      { q: 'Кайсы тилдер колдоого алынат?', a: 'Интерфейс англис, орус жана кыргыз тилдерин колдойт. Хедердеги вертикалдык тил которгучту колдонуңуз.' },
      { q: 'Кайсы офистер бар?', a: 'Долбоордо аэропорт жана шаар офистери бар: Манас, Ош, Бишкек, Ысык-Көл, Каракол жана Жалал-Абад, туристтик маршруттар үчүн деталдары менен.' },
    ],
    aboutEyebrow: '2026-жылы АЭУ студенттери түзгөн',
    aboutTitle: 'Кыргызстан туризми үчүн унаа ижара платформасы',
    aboutLead: 'Бул веб-платформа Ала-Тоо Эл аралык Университетинин студенттери тарабынан 2026-жылы туризмди колдоо, өлкө ичиндеги сапарларды ыңгайлуу кылуу жана конокторду жергиликтүү мобилдүүлүк менен байланыштыруу үчүн түзүлгөн.',
    aboutStoryTitle: 'Чыныгы туристтик миссиясы бар студенттик долбоор',
    aboutStoryText: 'CWD Rental React frontend жана Spring Boot backend системасын бириктирип, заманбап университеттик долбоор туризм маселесин кантип чече аларын көрсөтөт: ишенимдүү унаа брондоо, офистерди табуу жана партнерлердин унаасын коопсуз жарыялоо.',
    aboutTourismTitle: 'Өлкө ичинде ыңгайлуу саякат үчүн',
    aboutTourismText: 'Тажрыйба Кыргызстан маршруттарына багытталган: аэропорттон алуу, шаардык офистер, тоо сапарлары, көлгө баруу, аймактык жолдор жана жолго чыгаар алдында түшүнүктүү байланыш.',
    aboutFleetTitle: 'Автопарк, партнерлер жана админ көзөмөлү бир системада',
    aboutFleetText: 'Партнерлер сүрөттөрү жана деталдары менен унаа кошот, админдер жарыяларды бекитет, ижараларды башкарат, кооптуу колдонуучуларды себеп менен бан кылат жана тартипти сактайт.',
    aboutStats: [
      { value: '2026', label: 'долбоор башталган жыл' },
      { value: '3', label: 'интерфейс тили' },
      { value: '7', label: 'туристтик офис' },
      { value: '24/7', label: 'аэропорт колдоосу' },
    ],
    aboutHighlights: [
      'Ала-Тоо Эл аралык Университетинин студенттери түзгөн',
      'Ички туризмди жана аймактык сапарларды колдойт',
      'React, Spring Boot, JWT, OAuth2 жана PostgreSQL',
      'Партнер жана админ функциялары backend менен байланышкан',
    ],
    contactEyebrow: 'Долбоор байланыштары',
    contactTitle: 'CWD Rental командасы менен байланышыңыз',
    contactLead: 'Унаалар, офистер, партнер жарыялары, админ колдоосу же долбоор идеясы боюнча сурооңуз барбы? Билдирүү жөнөтүңүз же түз каналдарды колдонуңуз.',
    contactDirectTitle: 'Түз каналдар',
    contactFormTitle: 'Бизге билдирүү жөнөтүңүз',
    projectEmail: 'support@cwd-rental.kg',
    projectWhatsapp: '+996 700 100 100',
    projectInstagram: '@cwd.rental.kg',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    officeHours: 'Колдоо убактысы',
    officeHoursValue: '09:00 - 21:00, Бишкек убактысы',
    yourName: 'Атыңыз',
    yourEmail: 'Email дарегиңиз',
    yourMessage: 'Билдирүүңүз',
    messagePlaceholder: 'Эмне керек экенин жазыңыз: брондоо жардамы, унаа кошуу, офис маалыматы же долбоор боюнча пикир.',
    sendMessage: 'Билдирүү жөнөтүү',
    faqEyebrow: 'Жардам борбору',
    faqTitle: 'Көп берилген суроолор',
    faqLead: 'Брондоо, партнерлер, админ бекитүүсү, офистер, тилдер жана колдоо боюнча түшүнүктүү жооптор.',
    tourismEyebrow: 'Кыргызстан боюнча туристтик гид',
    tourismTitle: 'Алгач сезонду, анан жолду тандаңыз.',
    tourismLead: 'Көл пляждары, кызыл каньондор, ысык булактар, лыжа базалары жана мөңгү тропалары CWD офистер тармагы аркылуу жеткиликтүү. Адегенде маршрутту пландап, андан соң жолго ылайык унаа тандаңыз.',
    tourismTags: ['Көл', 'Капчыгай', 'Лыжа', 'Треккинг'],
    tourismFindCar: 'Сапарга унаа табуу',
    tourismChooseOffice: 'Алуу шаарын тандоо',
    tourismHeroImageAlt: 'Чолпон-Атадагы кооз Ысык-Көл пляжы',
    tourismLoopLabel: 'Ысык-Көл пляж айлампасы',
    tourismLoopDuration: '3-7 күн',
    tourismLoopText: 'Бишкектен баштап көлгө өтүңүз, жээк менен Караколго чейин жүрүңүз жана аба ырайына жараша пляждарды, капчыгайларды же ысык булактарды кошуңуз.',
    tourismSeasonEyebrow: 'Сезондук идеялар',
    tourismSeasonTitle: 'Даталарга гана эмес, маанайга жараша саякаттаңыз.',
    tourismSeasonLead: 'Жай көл жолдору жана боз үй лагерлери үчүн ылайыктуу. Кыш лыжа базалары жана кыска тоо күндөрү үчүн жакшы. Жаз жана күз тынчыраак жолдорду тартуулайт.',
    tourismSeasonCards: [
      {
        title: 'Ысык-Көлдүн жайкы жээги',
        time: 'Июнь - сентябрь',
        text: 'Чолпон-Ата, Бостери жана Тамчы пляждары жылуу суу, тоо көрүнүшү, суу оюн-зоогу, күн батышы жана маданий токтоолор менен айкалышат.',
        places: ['Чолпон-Ата пляжы', 'Бостери курорт аймагы', 'Тамчы тынч жээги', 'Петроглифтер музейи'],
      },
      {
        title: 'Капчыгайлар, көлдөр жана походдор',
        time: 'Июндун ортосунан сентябрга чейин',
        text: 'Каракол Жети-Өгүз, Алтын-Арашан ысык булактары, Ала-Көл треккинги, жашыл өрөөндөр жана түштүк маршруттар үчүн ыңгайлуу база.',
        places: ['Жети-Өгүз аскалары', 'Алтын-Арашан өрөөнү', 'Ала-Көл треги', 'Жыргаландагы походдор', 'Кара-Кой', 'Арсланбоб', 'Сары-Челек'],
      },
      {
        title: 'Лыжа жана альп дем алыштары',
        time: 'Декабрь - февраль',
        text: 'Кышында план өзгөрөт: Бишкек же Караколго жакын токтоп, карга ылайык унаа тандап, жол абалын текшерип, убакытты ийкемдүү кармаңыз.',
        places: ['Каракол лыжа базасы', 'Ала-Арча кышкы сейилдөөлөрү', 'Чуңкурчак склонду', 'Суусамыр өрөөнү'],
      },
    ],
    tourismBestPlacesEyebrow: 'Коноктор үчүн мыкты жерлер',
    tourismBestPlacesTitle: 'Биринчи маршрут үчүн кыска тизме.',
    tourismBestPlaces: [
      { name: 'Ысык-Көлдүн түндүк жээги', tag: 'Пляждар', detail: 'Көлгө биринчи сапар, сууга түшүү, суу оюн-зоогу жана жандуу жайкы кечтер үчүн жакшы.' },
      { name: 'Ысык-Көлдүн түштүк жээги', tag: 'Каньондор', detail: 'Тынчыраак айылдар, Сказка каньону, Барскоон шаркыратмалары, боз үй токтоолору жана кооз жолдор.' },
      { name: 'Каракол жана Жети-Өгүз', tag: 'Укмуш сапар', detail: 'Капчыгай сейилдөөлөрү, ат минүү, ысык булактар, көп күндүк треккинг жана тоо тамактары үчүн ыңгайлуу база.' },
      { name: 'Ала-Арча улуттук паркы', tag: 'Бир күндүк сапар', detail: 'Бишкекке эң жакын чоң тоо багыты: жеңил өрөөн сейилдөөлөрү жана мөңгү көрүнүшүнө татаалыраак жолдор.' },
      { name: 'Соң-Көл', tag: 'Көчмөн жашоо', detail: 'Жайкы боз үй лагерлери, аттар, кең жайлоо, салкын түндөр жана 3 000 метрден жогору чоң асман.' },
      { name: 'Алай өрөөнү жана Ленин чокусу', tag: 'Альпинизм', detail: 'Тажрыйбалуу туристтер, альпинисттер, фотографтар жана Памир маршруттары үчүн түштүктөгү бийик тоо көрүнүштөрү.' },
      { name: 'Кара-Кой', tag: 'Түштүк аймак', detail: 'Айыл пейзаждары, аймактык жолдор жана Ош тараптан ийкемдүү маршруттар үчүн тынч түштүк токтоосу.' },
      { name: 'Арсланбоб', tag: 'Жаңгак токою', detail: 'Жалал-Абад облусундагы шаркыратмалар, конок үйлөр, ат маршруттары жана белгилүү жаңгак токою бар сүйүктүү жер.' },
      { name: 'Сары-Челек', tag: 'Корук', detail: 'Жайкы жаратылыш, сүрөт тартуу жана түштүктө жай саякат үчүн көл жана токой маршруту.' },
    ],
    tourismDirections: 'Маршрут',
    tourismWikipedia: 'Wikipedia маалыматы',
    tourismBeforeRoad: 'Жолго чейин',
    tourismNotesTitle: 'Туристтер үчүн пайдалуу кеңештер',
    tourismTripNotes: [
      'Июль жана август айларына Ысык-Көлдөгү популярдуу жайларды алдын ала брондоңуз.',
      'Жайында да жылуу кийим алыңыз: бийик өрөөндөрдө күн баткандан кийин тез салкындайт.',
      'Түштүк жээк, капчыгайлар, Соң-Көл жана тоо жолдору үчүн клиренси бийик унаа жакшы.',
      'Альпинизм же алыс треккинг үчүн жергиликтүү гиддер менен жүрүп, уруксаттарды, аба ырайын жана камсыздандырууну текшериңиз.',
    ],
    tourismCarMatchTitle: 'Унаа тандоо',
    tourismCarMatchText: 'Шаардык жана түндүк көл маршруттарына көпчүлүк унаалар жарайт. Түштүк жээк, каньондор, жайлоо жолдору, түштүк аймактык жолдор жана кышкы ашуулар үчүн клиренси бийик жана дөңгөлөктөрү ишенимдүү унаа жакшы.',
    tourismPhotoSources: 'Фото булактары:',
    footerContactTitle: 'Долбоор байланыштары',
  },
};

const languages = [
  { code: 'en', labelKey: 'english', short: 'EN' },
  { code: 'ru', labelKey: 'russian', short: 'RU' },
  { code: 'kg', labelKey: 'kyrgyz', short: 'KG' },
];

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const t = (key, params) => {
    const value = dictionaries[lang]?.[key] ?? dictionaries.en[key] ?? key;
    return typeof value === 'function' ? value(params) : value;
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t, languages }}>
      {children}
    </LangContext.Provider>
  );
};
