spring.application.name=car-rental-backend
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8080}
server.forward-headers-strategy=framework

app.frontend.url=${FRONTEND_URL:http://localhost:5173}
app.backend.url=${BACKEND_URL:http://localhost:${server.port}}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:${app.frontend.url}}
app.admin.name=${APP_ADMIN_NAME:Eldos Kubatov}
app.admin.email=${APP_ADMIN_EMAIL:eldosweg773@gmail.com}
app.admin.password=${APP_ADMIN_PASSWORD:3240630505@}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/car-rental-system}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234567}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:change-this-secret-key-to-a-64-character-minimum-value-for-production-use-123456}
jwt.expiration=${JWT_EXPIRATION:86400000}

# ==========================================
# OAUTH2 REGISTRATIONS 
# ==========================================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=${app.backend.url}/login/oauth2/code/{registrationId}